"""added tables parks and campsites

Revision ID: 7a5d28454981
Revises: 
Create Date: 2023-08-17 11:14:46.470718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5d28454981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('entrance_fee', sa.Float(), nullable=False),
    sa.Column('has_trails', sa.Boolean(), nullable=True),
    sa.Column('has_RV_cleanout', sa.Boolean(), nullable=True),
    sa.Column('begin_camping_season', sa.Date(), nullable=True),
    sa.Column('end_camping_season', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campsites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('site_fee', sa.Float(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('has_bathroom', sa.Boolean(), nullable=True),
    sa.Column('has_grill', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campsites')
    op.drop_table('parks')
    # ### end Alembic commands ###
